// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1-devel
// 	protoc        v3.6.1
// source: client.proto

package client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//CToHType 客户端到大厅服务器的消息类型
type CToHType int32

const (
	CToHType_LoginReq         CToHType = 0 //登录请求
	CToHType_GetPlayerInfoReq CToHType = 1 //获取玩家信息请求
	CToHType_StartQueuingReq  CToHType = 2 //开始排队请求
	CToHType_StopQueuingReq   CToHType = 3 //取消排队请求
	CToHType_QuitHallReq      CToHType = 4 //退出请求
)

// Enum value maps for CToHType.
var (
	CToHType_name = map[int32]string{
		0: "LoginReq",
		1: "GetPlayerInfoReq",
		2: "StartQueuingReq",
		3: "StopQueuingReq",
		4: "QuitHallReq",
	}
	CToHType_value = map[string]int32{
		"LoginReq":         0,
		"GetPlayerInfoReq": 1,
		"StartQueuingReq":  2,
		"StopQueuingReq":   3,
		"QuitHallReq":      4,
	}
)

func (x CToHType) Enum() *CToHType {
	p := new(CToHType)
	*p = x
	return p
}

func (x CToHType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CToHType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[0].Descriptor()
}

func (CToHType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[0]
}

func (x CToHType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CToHType.Descriptor instead.
func (CToHType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

//HToCType 大厅服务器到客户端的消息类型
type HToCType int32

const (
	HToCType_LoginResp         HToCType = 0
	HToCType_GetPlayerInfoResp HToCType = 1
	HToCType_StartQueuingResp  HToCType = 2
	HToCType_StopQueuingResp   HToCType = 3
	HToCType_QuitHallResp      HToCType = 4
	HToCType_BroadcastType     HToCType = 15
)

// Enum value maps for HToCType.
var (
	HToCType_name = map[int32]string{
		0:  "LoginResp",
		1:  "GetPlayerInfoResp",
		2:  "StartQueuingResp",
		3:  "StopQueuingResp",
		4:  "QuitHallResp",
		15: "BroadcastType",
	}
	HToCType_value = map[string]int32{
		"LoginResp":         0,
		"GetPlayerInfoResp": 1,
		"StartQueuingResp":  2,
		"StopQueuingResp":   3,
		"QuitHallResp":      4,
		"BroadcastType":     15,
	}
)

func (x HToCType) Enum() *HToCType {
	p := new(HToCType)
	*p = x
	return p
}

func (x HToCType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HToCType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[1].Descriptor()
}

func (HToCType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[1]
}

func (x HToCType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HToCType.Descriptor instead.
func (HToCType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

type LoginErrorType int32

const (
	LoginErrorType_PhoneNotExist   LoginErrorType = 0 //手机号未注册
	LoginErrorType_WrongPassword   LoginErrorType = 1 //密码不正确
	LoginErrorType_AccountNotExist LoginErrorType = 2 //账户不存在
	LoginErrorType_DBInnerError    LoginErrorType = 3 //数据库内部错误
	LoginErrorType_HallInnerError  LoginErrorType = 4
)

// Enum value maps for LoginErrorType.
var (
	LoginErrorType_name = map[int32]string{
		0: "PhoneNotExist",
		1: "WrongPassword",
		2: "AccountNotExist",
		3: "DBInnerError",
		4: "HallInnerError",
	}
	LoginErrorType_value = map[string]int32{
		"PhoneNotExist":   0,
		"WrongPassword":   1,
		"AccountNotExist": 2,
		"DBInnerError":    3,
		"HallInnerError":  4,
	}
)

func (x LoginErrorType) Enum() *LoginErrorType {
	p := new(LoginErrorType)
	*p = x
	return p
}

func (x LoginErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoginErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[2].Descriptor()
}

func (LoginErrorType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[2]
}

func (x LoginErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoginErrorType.Descriptor instead.
func (LoginErrorType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

type QueueErrorType int32

const (
	QueueErrorType_CanNotStartGameServer QueueErrorType = 0
	QueueErrorType_CanNotStartGameRoom   QueueErrorType = 1
	QueueErrorType_WrongPlayerId         QueueErrorType = 2
	QueueErrorType_NoEnoughPlayer        QueueErrorType = 3
)

// Enum value maps for QueueErrorType.
var (
	QueueErrorType_name = map[int32]string{
		0: "CanNotStartGameServer",
		1: "CanNotStartGameRoom",
		2: "WrongPlayerId",
		3: "NoEnoughPlayer",
	}
	QueueErrorType_value = map[string]int32{
		"CanNotStartGameServer": 0,
		"CanNotStartGameRoom":   1,
		"WrongPlayerId":         2,
		"NoEnoughPlayer":        3,
	}
)

func (x QueueErrorType) Enum() *QueueErrorType {
	p := new(QueueErrorType)
	*p = x
	return p
}

func (x QueueErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QueueErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[3].Descriptor()
}

func (QueueErrorType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[3]
}

func (x QueueErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QueueErrorType.Descriptor instead.
func (QueueErrorType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

type GameType int32

const (
	GameType_NormalGameType GameType = 0
)

// Enum value maps for GameType.
var (
	GameType_name = map[int32]string{
		0: "NormalGameType",
	}
	GameType_value = map[string]int32{
		"NormalGameType": 0,
	}
)

func (x GameType) Enum() *GameType {
	p := new(GameType)
	*p = x
	return p
}

func (x GameType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GameType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[4].Descriptor()
}

func (GameType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[4]
}

func (x GameType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GameType.Descriptor instead.
func (GameType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

type GetPlayerInfoErrorType int32

const (
	GetPlayerInfoErrorType_IllegalPlayerId  GetPlayerInfoErrorType = 0 //非法玩家id(例如该玩家id没有被注册)
	GetPlayerInfoErrorType_HiddenPlayerInfo GetPlayerInfoErrorType = 1 //该玩家选择隐藏id
)

// Enum value maps for GetPlayerInfoErrorType.
var (
	GetPlayerInfoErrorType_name = map[int32]string{
		0: "IllegalPlayerId",
		1: "HiddenPlayerInfo",
	}
	GetPlayerInfoErrorType_value = map[string]int32{
		"IllegalPlayerId":  0,
		"HiddenPlayerInfo": 1,
	}
)

func (x GetPlayerInfoErrorType) Enum() *GetPlayerInfoErrorType {
	p := new(GetPlayerInfoErrorType)
	*p = x
	return p
}

func (x GetPlayerInfoErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetPlayerInfoErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_client_proto_enumTypes[5].Descriptor()
}

func (GetPlayerInfoErrorType) Type() protoreflect.EnumType {
	return &file_client_proto_enumTypes[5]
}

func (x GetPlayerInfoErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetPlayerInfoErrorType.Descriptor instead.
func (GetPlayerInfoErrorType) EnumDescriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

//客户端到大厅服务器的消息类型
type CToH struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType              CToHType              `protobuf:"varint,1,opt,name=msgType,proto3,enum=CToHType" json:"msgType,omitempty"`
	LoginRequest         *LoginRequest         `protobuf:"bytes,2,opt,name=loginRequest,proto3" json:"loginRequest,omitempty"`
	GetPlayerInfoRequest *GetPlayerInfoRequest `protobuf:"bytes,3,opt,name=getPlayerInfoRequest,proto3" json:"getPlayerInfoRequest,omitempty"`
	StartQueueRequest    *StartQueueRequest    `protobuf:"bytes,4,opt,name=startQueueRequest,proto3" json:"startQueueRequest,omitempty"`
	StopQueuingRequest   *StopQueuingRequest   `protobuf:"bytes,5,opt,name=stopQueuingRequest,proto3" json:"stopQueuingRequest,omitempty"`
	QuitHallRequest      *QuitHallRequest      `protobuf:"bytes,6,opt,name=quitHallRequest,proto3" json:"quitHallRequest,omitempty"`
}

func (x *CToH) Reset() {
	*x = CToH{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CToH) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CToH) ProtoMessage() {}

func (x *CToH) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CToH.ProtoReflect.Descriptor instead.
func (*CToH) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{0}
}

func (x *CToH) GetMsgType() CToHType {
	if x != nil {
		return x.MsgType
	}
	return CToHType_LoginReq
}

func (x *CToH) GetLoginRequest() *LoginRequest {
	if x != nil {
		return x.LoginRequest
	}
	return nil
}

func (x *CToH) GetGetPlayerInfoRequest() *GetPlayerInfoRequest {
	if x != nil {
		return x.GetPlayerInfoRequest
	}
	return nil
}

func (x *CToH) GetStartQueueRequest() *StartQueueRequest {
	if x != nil {
		return x.StartQueueRequest
	}
	return nil
}

func (x *CToH) GetStopQueuingRequest() *StopQueuingRequest {
	if x != nil {
		return x.StopQueuingRequest
	}
	return nil
}

func (x *CToH) GetQuitHallRequest() *QuitHallRequest {
	if x != nil {
		return x.QuitHallRequest
	}
	return nil
}

//大厅服务器到客户端的消息类型
type HToC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgType               HToCType               `protobuf:"varint,1,opt,name=msgType,proto3,enum=HToCType" json:"msgType,omitempty"`
	LoginResponse         *LoginResponse         `protobuf:"bytes,2,opt,name=loginResponse,proto3" json:"loginResponse,omitempty"`
	StartQueueResponse    *StartQueueResponse    `protobuf:"bytes,3,opt,name=StartQueueResponse,proto3" json:"StartQueueResponse,omitempty"`
	GetPlayerInfoResponse *GetPlayerInfoResponse `protobuf:"bytes,4,opt,name=getPlayerInfoResponse,proto3" json:"getPlayerInfoResponse,omitempty"`
	StopQueuingResponse   *StopQueuingResponse   `protobuf:"bytes,5,opt,name=stopQueuingResponse,proto3" json:"stopQueuingResponse,omitempty"`
	QuitHallResponse      *QuitHallResponse      `protobuf:"bytes,6,opt,name=quitHallResponse,proto3" json:"quitHallResponse,omitempty"`
	Broadcast             *Broadcast             `protobuf:"bytes,7,opt,name=broadcast,proto3" json:"broadcast,omitempty"`
}

func (x *HToC) Reset() {
	*x = HToC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HToC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HToC) ProtoMessage() {}

func (x *HToC) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HToC.ProtoReflect.Descriptor instead.
func (*HToC) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{1}
}

func (x *HToC) GetMsgType() HToCType {
	if x != nil {
		return x.MsgType
	}
	return HToCType_LoginResp
}

func (x *HToC) GetLoginResponse() *LoginResponse {
	if x != nil {
		return x.LoginResponse
	}
	return nil
}

func (x *HToC) GetStartQueueResponse() *StartQueueResponse {
	if x != nil {
		return x.StartQueueResponse
	}
	return nil
}

func (x *HToC) GetGetPlayerInfoResponse() *GetPlayerInfoResponse {
	if x != nil {
		return x.GetPlayerInfoResponse
	}
	return nil
}

func (x *HToC) GetStopQueuingResponse() *StopQueuingResponse {
	if x != nil {
		return x.StopQueuingResponse
	}
	return nil
}

func (x *HToC) GetQuitHallResponse() *QuitHallResponse {
	if x != nil {
		return x.QuitHallResponse
	}
	return nil
}

func (x *HToC) GetBroadcast() *Broadcast {
	if x != nil {
		return x.Broadcast
	}
	return nil
}

//登录有关
type LoginRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PhoneNum string `protobuf:"bytes,1,opt,name=phoneNum,proto3" json:"phoneNum,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{2}
}

func (x *LoginRequest) GetPhoneNum() string {
	if x != nil {
		return x.PhoneNum
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool           `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`                           //登录是否成功
	Error LoginErrorType `protobuf:"varint,2,opt,name=error,proto3,enum=LoginErrorType" json:"error,omitempty"` //如果不成功返回错误信息
	PInfo *PlayerInfo    `protobuf:"bytes,3,opt,name=pInfo,proto3" json:"pInfo,omitempty"`                      //如果成功返回玩家信息
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{3}
}

func (x *LoginResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *LoginResponse) GetError() LoginErrorType {
	if x != nil {
		return x.Error
	}
	return LoginErrorType_PhoneNotExist
}

func (x *LoginResponse) GetPInfo() *PlayerInfo {
	if x != nil {
		return x.PInfo
	}
	return nil
}

type PlayerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId  int32  `protobuf:"varint,1,opt,name=PlayerId,proto3" json:"PlayerId,omitempty"`
	NickName  string `protobuf:"bytes,2,opt,name=NickName,proto3" json:"NickName,omitempty"`
	GameCount int32  `protobuf:"varint,3,opt,name=GameCount,proto3" json:"GameCount,omitempty"` //参与游戏数
	KillNum   int32  `protobuf:"varint,4,opt,name=KillNum,proto3" json:"KillNum,omitempty"`     //总击杀数
	MaxKill   int32  `protobuf:"varint,5,opt,name=MaxKill,proto3" json:"MaxKill,omitempty"`     //最高单局击杀数
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerInfo) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *PlayerInfo) GetGameCount() int32 {
	if x != nil {
		return x.GameCount
	}
	return 0
}

func (x *PlayerInfo) GetKillNum() int32 {
	if x != nil {
		return x.KillNum
	}
	return 0
}

func (x *PlayerInfo) GetMaxKill() int32 {
	if x != nil {
		return x.MaxKill
	}
	return 0
}

//排队有关
type StartQueueRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`               //待排队的玩家id
	GameType GameType `protobuf:"varint,2,opt,name=gameType,proto3,enum=GameType" json:"gameType,omitempty"` //游戏类型
}

func (x *StartQueueRequest) Reset() {
	*x = StartQueueRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueueRequest) ProtoMessage() {}

func (x *StartQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueueRequest.ProtoReflect.Descriptor instead.
func (*StartQueueRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{5}
}

func (x *StartQueueRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *StartQueueRequest) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_NormalGameType
}

type StartQueueResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok                   bool                  `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	GameServerConnection *GameServerConnection `protobuf:"bytes,2,opt,name=gameServerConnection,proto3" json:"gameServerConnection,omitempty"` //如果排队成功,返回gameServer的联系方式
	Error                QueueErrorType        `protobuf:"varint,3,opt,name=error,proto3,enum=QueueErrorType" json:"error,omitempty"`          //如果排队失败,返回错误信息
}

func (x *StartQueueResponse) Reset() {
	*x = StartQueueResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartQueueResponse) ProtoMessage() {}

func (x *StartQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartQueueResponse.ProtoReflect.Descriptor instead.
func (*StartQueueResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{6}
}

func (x *StartQueueResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *StartQueueResponse) GetGameServerConnection() *GameServerConnection {
	if x != nil {
		return x.GameServerConnection
	}
	return nil
}

func (x *StartQueueResponse) GetError() QueueErrorType {
	if x != nil {
		return x.Error
	}
	return QueueErrorType_CanNotStartGameServer
}

type GameServerConnection struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip     string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port   string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	RoomId int32  `protobuf:"varint,3,opt,name=roomId,proto3" json:"roomId,omitempty"`
}

func (x *GameServerConnection) Reset() {
	*x = GameServerConnection{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GameServerConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameServerConnection) ProtoMessage() {}

func (x *GameServerConnection) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameServerConnection.ProtoReflect.Descriptor instead.
func (*GameServerConnection) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{7}
}

func (x *GameServerConnection) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *GameServerConnection) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *GameServerConnection) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

type StopQueuingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	GameType GameType `protobuf:"varint,2,opt,name=gameType,proto3,enum=GameType" json:"gameType,omitempty"` //游戏类型
}

func (x *StopQueuingRequest) Reset() {
	*x = StopQueuingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopQueuingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopQueuingRequest) ProtoMessage() {}

func (x *StopQueuingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopQueuingRequest.ProtoReflect.Descriptor instead.
func (*StopQueuingRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{8}
}

func (x *StopQueuingRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *StopQueuingRequest) GetGameType() GameType {
	if x != nil {
		return x.GameType
	}
	return GameType_NormalGameType
}

type StopQueuingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *StopQueuingResponse) Reset() {
	*x = StopQueuingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopQueuingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopQueuingResponse) ProtoMessage() {}

func (x *StopQueuingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopQueuingResponse.ProtoReflect.Descriptor instead.
func (*StopQueuingResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{9}
}

func (x *StopQueuingResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

//获取玩家信息有关
type GetPlayerInfoRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
}

func (x *GetPlayerInfoRequest) Reset() {
	*x = GetPlayerInfoRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoRequest) ProtoMessage() {}

func (x *GetPlayerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{10}
}

func (x *GetPlayerInfoRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPlayerInfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok    bool        `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	PInfo *PlayerInfo `protobuf:"bytes,2,opt,name=pInfo,proto3" json:"pInfo,omitempty"`
}

func (x *GetPlayerInfoResponse) Reset() {
	*x = GetPlayerInfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPlayerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerInfoResponse) ProtoMessage() {}

func (x *GetPlayerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerInfoResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{11}
}

func (x *GetPlayerInfoResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *GetPlayerInfoResponse) GetPInfo() *PlayerInfo {
	if x != nil {
		return x.PInfo
	}
	return nil
}

//退出大厅有关
type QuitHallRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId int32 `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"` //实际上没有什么用...
}

func (x *QuitHallRequest) Reset() {
	*x = QuitHallRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitHallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitHallRequest) ProtoMessage() {}

func (x *QuitHallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitHallRequest.ProtoReflect.Descriptor instead.
func (*QuitHallRequest) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{12}
}

func (x *QuitHallRequest) GetPlayerId() int32 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type QuitHallResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *QuitHallResponse) Reset() {
	*x = QuitHallResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QuitHallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuitHallResponse) ProtoMessage() {}

func (x *QuitHallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuitHallResponse.ProtoReflect.Descriptor instead.
func (*QuitHallResponse) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{13}
}

func (x *QuitHallResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

//广播有关
type Broadcast struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Broadcast) Reset() {
	*x = Broadcast{}
	if protoimpl.UnsafeEnabled {
		mi := &file_client_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Broadcast) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Broadcast) ProtoMessage() {}

func (x *Broadcast) ProtoReflect() protoreflect.Message {
	mi := &file_client_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Broadcast.ProtoReflect.Descriptor instead.
func (*Broadcast) Descriptor() ([]byte, []int) {
	return file_client_proto_rawDescGZIP(), []int{14}
}

func (x *Broadcast) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_client_proto protoreflect.FileDescriptor

var file_client_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xec,
	0x02, 0x0a, 0x04, 0x43, 0x54, 0x6f, 0x48, 0x12, 0x23, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x43, 0x54, 0x6f, 0x48, 0x54,
	0x79, 0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x31, 0x0a, 0x0c,
	0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x0c, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x49, 0x0a, 0x14, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x14, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x40, 0x0a, 0x11, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x11, 0x73, 0x74, 0x61, 0x72, 0x74,
	0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x12,
	0x73, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x51,
	0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x12, 0x73,
	0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x3a, 0x0a, 0x0f, 0x71, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x51, 0x75, 0x69,
	0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0f, 0x71, 0x75,
	0x69, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xa5, 0x03,
	0x0a, 0x04, 0x48, 0x54, 0x6f, 0x43, 0x12, 0x23, 0x0a, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x48, 0x54, 0x6f, 0x43, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x34, 0x0a, 0x0d, 0x6c,
	0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0d, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x43, 0x0a, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x12, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x15, 0x67, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x15, 0x67,
	0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x46, 0x0a, 0x13, 0x73, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75,
	0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x13, 0x73, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65,
	0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x10,
	0x71, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x51, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x10, 0x71, 0x75, 0x69, 0x74, 0x48,
	0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x28, 0x0a, 0x09, 0x62,
	0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x52, 0x09, 0x62, 0x72, 0x6f, 0x61,
	0x64, 0x63, 0x61, 0x73, 0x74, 0x22, 0x46, 0x0a, 0x0c, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x22, 0x69, 0x0a,
	0x0d, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x25,
	0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x05, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x96, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x47, 0x61, 0x6d, 0x65, 0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x4b, 0x69, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x4b, 0x69, 0x6c, 0x6c, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x78, 0x4b, 0x69,
	0x6c, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4d, 0x61, 0x78, 0x4b, 0x69, 0x6c,
	0x6c, 0x22, 0x56, 0x0a, 0x11, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x96, 0x01, 0x0a, 0x12, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x51, 0x75, 0x65, 0x75, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x49, 0x0a, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x14, 0x67, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x51, 0x75, 0x65,
	0x75, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x52, 0x0a, 0x14, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f,
	0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x22, 0x57, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x70, 0x51, 0x75,
	0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x47, 0x61, 0x6d,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22,
	0x25, 0x0a, 0x13, 0x53, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x32, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65,
	0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x12, 0x21, 0x0a, 0x05, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x05, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x2d, 0x0a, 0x0f, 0x51, 0x75, 0x69, 0x74, 0x48, 0x61,
	0x6c, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x49, 0x64, 0x22, 0x22, 0x0a, 0x10, 0x51, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c,
	0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x22, 0x1d, 0x0a, 0x09, 0x42, 0x72, 0x6f,
	0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x2a, 0x68, 0x0a, 0x08, 0x43, 0x54, 0x6f, 0x48,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12, 0x13, 0x0a, 0x0f, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x10, 0x02, 0x12, 0x12, 0x0a,
	0x0e, 0x53, 0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x10,
	0x03, 0x12, 0x0f, 0x0a, 0x0b, 0x51, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x71,
	0x10, 0x04, 0x2a, 0x80, 0x01, 0x0a, 0x08, 0x48, 0x54, 0x6f, 0x43, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0d, 0x0a, 0x09, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x10, 0x00, 0x12, 0x15,
	0x0a, 0x11, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x65, 0x73, 0x70, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x51, 0x75,
	0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x10, 0x02, 0x12, 0x13, 0x0a, 0x0f, 0x53,
	0x74, 0x6f, 0x70, 0x51, 0x75, 0x65, 0x75, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x10, 0x03,
	0x12, 0x10, 0x0a, 0x0c, 0x51, 0x75, 0x69, 0x74, 0x48, 0x61, 0x6c, 0x6c, 0x52, 0x65, 0x73, 0x70,
	0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x42, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x0f, 0x2a, 0x71, 0x0a, 0x0e, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x50, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0x00, 0x12, 0x11, 0x0a, 0x0d, 0x57, 0x72,
	0x6f, 0x6e, 0x67, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x10, 0x01, 0x12, 0x13, 0x0a,
	0x0f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74,
	0x10, 0x02, 0x12, 0x10, 0x0a, 0x0c, 0x44, 0x42, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x10, 0x03, 0x12, 0x12, 0x0a, 0x0e, 0x48, 0x61, 0x6c, 0x6c, 0x49, 0x6e, 0x6e, 0x65,
	0x72, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x10, 0x04, 0x2a, 0x6b, 0x0a, 0x0e, 0x51, 0x75, 0x65, 0x75,
	0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a, 0x15, 0x43, 0x61,
	0x6e, 0x4e, 0x6f, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x10, 0x00, 0x12, 0x17, 0x0a, 0x13, 0x43, 0x61, 0x6e, 0x4e, 0x6f, 0x74, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x47, 0x61, 0x6d, 0x65, 0x52, 0x6f, 0x6f, 0x6d, 0x10, 0x01, 0x12, 0x11,
	0x0a, 0x0d, 0x57, 0x72, 0x6f, 0x6e, 0x67, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x10,
	0x02, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x6f, 0x45, 0x6e, 0x6f, 0x75, 0x67, 0x68, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x10, 0x03, 0x2a, 0x1e, 0x0a, 0x08, 0x47, 0x61, 0x6d, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x47, 0x61, 0x6d, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x10, 0x00, 0x2a, 0x43, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x13, 0x0a, 0x0f, 0x49, 0x6c, 0x6c, 0x65, 0x67, 0x61, 0x6c, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x49, 0x64, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x10, 0x01, 0x32, 0x25, 0x0a, 0x06, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x05, 0x53, 0x65, 0x72, 0x76, 0x65, 0x12, 0x05, 0x2e,
	0x43, 0x54, 0x6f, 0x48, 0x1a, 0x05, 0x2e, 0x48, 0x54, 0x6f, 0x43, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x3b, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_client_proto_rawDescOnce sync.Once
	file_client_proto_rawDescData = file_client_proto_rawDesc
)

func file_client_proto_rawDescGZIP() []byte {
	file_client_proto_rawDescOnce.Do(func() {
		file_client_proto_rawDescData = protoimpl.X.CompressGZIP(file_client_proto_rawDescData)
	})
	return file_client_proto_rawDescData
}

var file_client_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_client_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_client_proto_goTypes = []interface{}{
	(CToHType)(0),                 // 0: CToHType
	(HToCType)(0),                 // 1: HToCType
	(LoginErrorType)(0),           // 2: LoginErrorType
	(QueueErrorType)(0),           // 3: QueueErrorType
	(GameType)(0),                 // 4: GameType
	(GetPlayerInfoErrorType)(0),   // 5: GetPlayerInfoErrorType
	(*CToH)(nil),                  // 6: CToH
	(*HToC)(nil),                  // 7: HToC
	(*LoginRequest)(nil),          // 8: LoginRequest
	(*LoginResponse)(nil),         // 9: LoginResponse
	(*PlayerInfo)(nil),            // 10: PlayerInfo
	(*StartQueueRequest)(nil),     // 11: StartQueueRequest
	(*StartQueueResponse)(nil),    // 12: StartQueueResponse
	(*GameServerConnection)(nil),  // 13: GameServerConnection
	(*StopQueuingRequest)(nil),    // 14: StopQueuingRequest
	(*StopQueuingResponse)(nil),   // 15: StopQueuingResponse
	(*GetPlayerInfoRequest)(nil),  // 16: GetPlayerInfoRequest
	(*GetPlayerInfoResponse)(nil), // 17: GetPlayerInfoResponse
	(*QuitHallRequest)(nil),       // 18: QuitHallRequest
	(*QuitHallResponse)(nil),      // 19: QuitHallResponse
	(*Broadcast)(nil),             // 20: Broadcast
}
var file_client_proto_depIdxs = []int32{
	0,  // 0: CToH.msgType:type_name -> CToHType
	8,  // 1: CToH.loginRequest:type_name -> LoginRequest
	16, // 2: CToH.getPlayerInfoRequest:type_name -> GetPlayerInfoRequest
	11, // 3: CToH.startQueueRequest:type_name -> StartQueueRequest
	14, // 4: CToH.stopQueuingRequest:type_name -> StopQueuingRequest
	18, // 5: CToH.quitHallRequest:type_name -> QuitHallRequest
	1,  // 6: HToC.msgType:type_name -> HToCType
	9,  // 7: HToC.loginResponse:type_name -> LoginResponse
	12, // 8: HToC.StartQueueResponse:type_name -> StartQueueResponse
	17, // 9: HToC.getPlayerInfoResponse:type_name -> GetPlayerInfoResponse
	15, // 10: HToC.stopQueuingResponse:type_name -> StopQueuingResponse
	19, // 11: HToC.quitHallResponse:type_name -> QuitHallResponse
	20, // 12: HToC.broadcast:type_name -> Broadcast
	2,  // 13: LoginResponse.error:type_name -> LoginErrorType
	10, // 14: LoginResponse.pInfo:type_name -> PlayerInfo
	4,  // 15: StartQueueRequest.gameType:type_name -> GameType
	13, // 16: StartQueueResponse.gameServerConnection:type_name -> GameServerConnection
	3,  // 17: StartQueueResponse.error:type_name -> QueueErrorType
	4,  // 18: StopQueuingRequest.gameType:type_name -> GameType
	10, // 19: GetPlayerInfoResponse.pInfo:type_name -> PlayerInfo
	6,  // 20: Client.Serve:input_type -> CToH
	7,  // 21: Client.Serve:output_type -> HToC
	21, // [21:22] is the sub-list for method output_type
	20, // [20:21] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_client_proto_init() }
func file_client_proto_init() {
	if File_client_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_client_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CToH); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HToC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LoginResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlayerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartQueueRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartQueueResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GameServerConnection); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopQueuingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopQueuingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerInfoRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPlayerInfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitHallRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QuitHallResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_client_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Broadcast); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_client_proto_rawDesc,
			NumEnums:      6,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_client_proto_goTypes,
		DependencyIndexes: file_client_proto_depIdxs,
		EnumInfos:         file_client_proto_enumTypes,
		MessageInfos:      file_client_proto_msgTypes,
	}.Build()
	File_client_proto = out.File
	file_client_proto_rawDesc = nil
	file_client_proto_goTypes = nil
	file_client_proto_depIdxs = nil
}
